### PR TITLE
pls to help

### PR DESCRIPTION
**Pull request by nimejia**
added name (fingers crossed!)

### CODE REVIEW

**Comment by Hypaethral** [comment]
Nice job @nimejia!  Usually you wouldn't merge your own pull requests right away; give people a chance to look it over and comment and stuff by adding reviewers:

screen shot 2017-03-01 at 10 14 02

I dunno how strongly @dnaf feels about this, but we might mandate that workflow if there are enough people contributing.  That way we minimize merge conflicts and can ensure everyone gets to see how the code being added works to solve a problem.

**Comment by nimejia** [comment]
Thanks for telling me, I'll do that next time.

**Comment by ghost** [comment]
this makes sense haha. tbh we should probably mandate that workflow as it is best practice to peer review

**Review by Hypaethral — COMMENTED** [review]
test

**Pull request merged**
